version: '2'

services:
  nginx:
    restart: always
    build: nginx
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    links:
      - api:api
      - web:web

  api:
    container_name: api
    restart: always
#    image: monetario/api
    build: ./core
    env_file: .environment
    volumes:
      - ./core:/opt/monetario/core
    expose:
      - "8000/tcp"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    command: python manage.py runserver -h 0.0.0.0 -p 8000

  web:
    container_name: web
    restart: always
    image: monetario/web
    volumes:
      - ./web:/opt/monetario/web
    expose:
      - "9000/tcp"
    ports:
      - "9000:9000"
    depends_on:
      - api
    command: python manage.py runserver -h 0.0.0.0 -p 9000

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redisdatavolume:/var/lib/redis
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    restart: always
    build: ./postgres
    volumes:
      - postgresdatavolume:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432/tcp"

volumes:
  postgresdatavolume:
    driver: local

  redisdatavolume:
    driver: local
