nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  links:
    - api:api
    - web:web

api:
  container_name: api
  restart: always
  build: ./api
  env_file: .environment
  volumes:
    - ./api/core:/opt/monetario-core
  expose:
    - "8000"
  links:
    - postgres:postgres
  command: python manage.py runserver -h 0.0.0.0 -p 8000

web:
  container_name: web
  restart: always
  build: ./web
  volumes:
    - ./web/web:/opt/monetario-web
  expose:
    - "9000"
  command: python manage.py runserver -h 0.0.0.0 -p 9000

postgres:
  container_name: postgres
  restart: always
  build: ./postgres
  ports:
    - "5432"

pgdata:
  image: busybox
  restart: always
  volumes:
    - /var/lib/postgresql
  command: "true"

redis:
  container_name: redis
  restart: always
  image: redis:latest
